// <auto-generated />
namespace Data1901321073.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class First : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "202106061352024_First"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
